inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**
    - db/migrate/**
    - node_modules/node-sass/src/libsass/contrib/**
    - node_modules/node-sass/src/libsass/**
    - config/initializers/**
    - config/**

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/controllers/sessions_controller.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/admin/tutorials_controller.rb'
    - 'app/models/invite_maker.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Lint/UselessAssignment:
  Exclude:
    - 'spec/features/user/user_can_see_list_of_bookmarks.rb'
    - 'spec/models/tutorial_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**'
    - 'spec/mailers/**'
    - 'spec/models/**'
    - 'spec/features/user/**'
    - 'spec/features/visitor/**'
    - 'spec/presenters/**'
    - 'spec/requests/api/v1/**'
    - 'spec/services/**'
    - 'lib/tasks/**'

Metrics/LineLength:
  Exclude:
    - 'lib/tasks/youtube_seed.rake'
    - 'spec/rails_helper.rb'
    - 'spec/models/invite_maker_spec.rb'
    - 'spec/features/user/user_can_invite_github_users_to_our_site_spec.rb'
    - 'app/models/invite_maker.rb'
    - 'app/controllers/admin/api/v1/tutorial_sequencer_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/rails_helper.rb'
