inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**
    - db/migrate/**
    - node_modules/node-sass/src/libsass/contrib/**
    - node_modules/node-sass/src/libsass/**
    - config/initializers/**
    - config/**

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Encoding:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/models/**'
    - 'spec/features/vistors/**'
    - 'spec/features/user/**'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/controllers/sessions_controller.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/admin/tutorials_controller.rb'
    - 'app/models/invite_maker.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Lint/UselessAssignment:
  Exclude:
    - 'spec/features/vistors/**'
    - 'spec/models/tutorial_spec.rb'
    - 'spec/requests/api/v1/**'
    - 'spec/presenters/**'
    - 'spec/features/user/**'
    - 'spec/features/admin/**'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/features/vistors/**'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'app/services/tutorial_sequencer.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/admin/videos_controller.rb'
    - 'app/controllers/friendships_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**'
    - 'spec/mailers/**'
    - 'spec/models/**'
    - 'spec/features/user/**'
    - 'spec/features/visitors/**'
    - 'spec/presenters/**'
    - 'spec/requests/api/v1/**'
    - 'spec/services/**'
    - 'lib/tasks/**'
    - 'spec/features/vistors/visitor_can_register_spec.rb'
    - 'spec/features/user/user_sees_all_bookmarked_segments_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'lib/tasks/youtube_seed.rake'
    - 'spec/rails_helper.rb'
    - 'spec/models/**'
    - 'app/controllers/**'
    - 'spec/features/vistors/visitor_can_register_spec.rb'
    - 'spec/features/user/**'
    - 'spec/features/admin/**'
    - 'config/environments/**'
    - 'app/models/user.rb'
    - 'spec/factories/tutorials.rb'
    - 'app/models/github_user.rb'
    - 'app/controllers/admin/**'
    - 'app/mailers/user_mailer.rb'
    - 'Rakefile'
    - 'app/controllers/admin/api/v1/tutorial_sequencer_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'app/controllers/friendships_controller.rb'
    - 'app/controllers/admin/api/v1/tutorial_sequencer_controller.rb'
    - 'app/mailers/user_mailer.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/friendships_controller.rb'

Naming/PredicateName:
  Exclude:
    - 'app/models/github_user.rb'
